# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e277ad5b9acaecf2eebef4c3181b48e0f0ba1159dfb70b11ebfac7b3006adefe1b253051069c58ed76bacd1615afb62e62abfc309ef19801753d1eca054b9fb7

test:
  secret_key_base: 6da260e366c2b57cd2fbcdb1903e60b8c5d85e86fecfed28ec7f72d2078380ecd113b2668c63340913128101e7cfd0de528b08c5bd441a094cb8a7fd1dd49004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
